version: "3"

networks:
  app-tier:
    driver: bridge

services:
  gunicorn-backend:
    restart: always
    container_name: gunicorn-backend
    build:
      context: .
      args:
        Django_secret_key: "${Django_secret_key}"
    #    volumes:
    #      - .:/code
    networks:
      - app-tier
    ports:
      - "8000:8000"

  nginx-backend:
    restart: always
    container_name: nginx-backend
    build: ./nginx
    volumes:
      - ./nginx/logs:/var/backend-logs
    expose:
      - "80"
      - "443"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-tier
    depends_on:
      - gunicorn-backend
    environment:
      - NGINX_HOST=0.0.0.0
      - NGINX_PORT=80
