version: "3"

networks:
  app-tier:
    driver: bridge
  db-tier:
    driver: bridge

services:
  gunicorn-backend:
    restart: always
    container_name: gunicorn-backend
    build:
      context: .
      args:
        Django_secret_key: "${Django_secret_key}"
        DJANGO_SUPERUSER_PASSWORD: "${DJANGO_SUPERUSER_PASSWORD}"
        DJANGO_SUPERUSER_USERNAME: "${DJANGO_SUPERUSER_USERNAME}"
        DJANGO_SUPERUSER_EMAIL: "${DJANGO_SUPERUSER_EMAIL}"
    #    volumes:
    #      - .:/code
    volumes:
      - ./static/:/code/static/
    networks:
      - app-tier
      - db-tier
    ports:
      - "8000:8000"
    depends_on:
      - database

  nginx-backend:
    restart: always
    container_name: nginx-backend
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    volumes:
      - ./logs:/var/backend-logs
      - ./static/:/static/
    expose:
      - "80"
      - "443"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-tier
    depends_on:
      - gunicorn-backend
    environment:
      - NGINX_HOST=0.0.0.0
      - NGINX_PORT=80

  database:
    image: "postgres"
    environment:
      - PGDATA=/var/lib/postgresql/data/django/
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lbs_platform
    networks:
      - db-tier
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data/django/
