version: "3"

networks:
  app-tier:
    driver: bridge
  db-tier:
    driver: bridge

services:
  gunicorn-backend:
    restart: always
    container_name: gunicorn-backend
    build: .
    environment:
      - Django_secret_key=${Django_secret_key}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
    volumes:
      - ./:/code
      - "/home/ubuntu/LBS-Platform/jenkins/jenkins_home/workspace:/var/jenkins_home/workspace"
    networks:
      - app-tier
      - db-tier
    expose:
      - 8000
    depends_on:
      - database
    privileged: true

  nginx-backend:
    restart: always
    container_name: nginx-backend
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    volumes:
      - ./logs:/var/backend-logs
      - ./static/:/static/
    ports:
      - "80:80"
      - "5001:80"
      - "443:443"
    networks:
      - app-tier
    depends_on:
      - gunicorn-backend
    environment:
      - NGINX_HOST=0.0.0.0
      - NGINX_PORT=80

  database:
    image: "postgres"
    environment:
      - PGDATA=/var/lib/postgresql/data/django/
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - db-tier
    volumes:
      - ./data/db:/var/lib/postgresql/data/django/
